/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kayak.sequential_counter.counter;

public class Counter {

    public static void countUp(int start, int end) {
        System.out.println(start);
        if (start != end) countUp(start + 1, end);
    }

    public static void countUpAndDown(int start, int end) {
        System.out.println(start);
        if (end == start) return;
        countUpAndDown(start + 1, end);
        System.out.println(start);
    }
}
